font_family JetBrainsMono Nerd Font
font_size 12.0

background_opacity 0.92
background #0e1016
foreground #e6e6e6

shell /usr/bin/zsh
copy_on_select yes
window_padding_width 8

# colors
color8  #a8a8a8
color7  #cfcfcf
color15 #ffffff
color6  #8bd5ca
color3  #f5c26b
color1  #ff6b6b

# cursor + selection
cursor_shape beam
cursor #8bd5ca
cursor_text_color #0e1016

selection_background #8bd5ca
selection_foreground #0e1016

# tabs
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted

active_tab_foreground #ffffff
active_tab_background #0f111a
inactive_tab_foreground #a8a8a8
inactive_tab_background #0f111a
active_tab_font_style bold