font_family JetBrainsMono Nerd Font
font_size 12.0

background #0a0a0a
foreground #e0e0e0
background_opacity 0.95

window_padding_width 6

shell /usr/bin/zsh
copy_on_select yes

cursor_shape block
cursor #e6a34a
cursor_text_color #000000

selection_background #2a1a12
selection_foreground #ffffff

color1  #c92a1a  
color3  #e6a34a   
color11 #f5c26b   
color7  #ddd6cf
color8  #6b625b
color15 #ffffff

tab_bar_edge none