font_family JetBrainsMono Nerd Font
font_size 12.0
copy_on_select yes

background #11161d
foreground #e6e6e6
background_opacity 0.96

window_padding_width 8

cursor_shape block
cursor #8aa7c1
cursor_text_color #1e1e1e

selection_background #1b2530
selection_foreground #ffffff

color0  #1e1e1e
color8  #6b6b6b

color1  #ff6b6b
color3  #e6a34a
color4  #4fc3f7
color7  #e6e6e6
color15 #ffffff

tab_bar_edge none
