# -*- conf -*-

layer=top
anchor=top-right

edge-margin-vertical=10
edge-margin-horizontal=10
notification-margin=10

background=303030ff

border-color=606060ff
border-radius=0
border-size=1

padding-vertical=10
padding-horizontal=12

title-font=monospace:size=10
title-color=eeeeeeff
title-format=<b>%a</b>

summary-font=monospace:size=10
summary-color=bbbbbbff
summary-format=%s

body-font=monospace:size=10
body-color=bbbbbbff
body-format=%b

progress-bar-height=3
progress-color=005577ff
progress-style=bar

default-timeout=5

# Urgency levels

[low]
background=303030ff
border-color=606060ff
title-color=888888ff
summary-color=888888ff
body-color=888888ff

[normal]
background=303030ff
border-color=606060ff
title-color=eeeeeeff
summary-color=bbbbbbff
body-color=bbbbbbff

[critical]
background=303030ff
border-color=770000ff
title-color=eeeeeeff
summary-color=eeeeeeff
body-color=eeeeeeff
